YCloudYUSA/yusaopeny_docs

- content/en/docs/user-documentation/layout-builder/_index.md
> Add lb stub

- .github/workflows/gh-pages.yml
Should resolve deprecation notices in builds. https://github.com/YCloudYUSA/yusaopeny_docs/actions/runs/3584213435
> Update gh-pages automation

- content/en/docs/user-documentation/layout-builder/_index.md
- content/en/docs/user-documentation/layout-builder/accordion/_index.md
- content/en/docs/user-documentation/layout-builder/cards/_index.md
- content/en/docs/user-documentation/layout-builder/carousel/_index.md
- content/en/docs/user-documentation/layout-builder/grid-cta/_index.md
- content/en/docs/user-documentation/layout-builder/hero-banner/_index.md
- content/en/docs/user-documentation/layout-builder/ping-pong/_index.md
- content/en/docs/user-documentation/layout-builder/promo-card/_index.md
- content/en/docs/user-documentation/layout-builder/simple-menu/_index.md
- content/en/docs/user-documentation/layout-builder/statistics/_index.md
- content/en/docs/user-documentation/layout-builder/table/_index.md
- content/en/docs/user-documentation/layout-builder/tabs/_index.md
- content/en/docs/user-documentation/layout-builder/webform/_index.md
add links to youtube for LB stuff and clean up
> DS-108 video links

- assets/scss/_styles_project.scss
- content/en/docs/glossary/_index.md
https://yusa.atlassian.net/browse/DS-292
Adds a Glossary page to help new folks get acclimated to our great big world.
> DS-292 Add glossary

- content/en/docs/content-structure/layout-builder/_index.md
Addresses: https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1673391760952489
> Minor layout builder documentation revisions

- content/en/docs/development/Daxko.md
Addresses: https://yusa.atlassian.net/browse/DS-279
Needs-feedback-from: @froboy
Referenced-by: https://git.drupalcode.org/project/groupexpro/-/compare/1.0.6...1.0.x?from_project_id=75887&straight=false
> feat: Add deprecation notice

- content/en/docs/content-structure/layout-builder/_index.md
Changed name of lb_tables component to lb_simple_content.
> docs: Updated lb_tables to lb_simple_content

- config.toml
- content/en/docs/development/Onboarding_to_YUSA_OpenY.md
- content/en/docs/wiki/Sandboxes.md
Clean up and consolidate Sandboxes info.
- Fixed and deduped info on https://ds-docs.y.org/docs/development/onboarding_to_yusa_openy/
- Update and reorganized https://ds-docs.y.org/docs/wiki/sandboxes/
- Updated /community links and added YUSA email address.
> [DS-276] Sandboxes

- content/en/blog/news/lb-2023-roadmap.md
- content/en/docs/content-structure/_index.md
- content/en/docs/contribution-guidelines/_index.md
- content/en/docs/development/_index.md
- content/en/docs/glossary/_index.md
- content/en/docs/user-documentation/content-types/branch/_index.md
- content/en/docs/user-documentation/content-types/lb-article/_index.md
- content/en/docs/user-documentation/content-types/lb-event/_index.md
- content/en/docs/user-documentation/layout-builder/_index.md
- content/en/docs/user-documentation/layout-builder/breadcrumbs/_index.md
- content/en/docs/user-documentation/layout-builder/modal/_index.md
- content/en/docs/user-documentation/layout-builder/partners/_index.md
- content/en/docs/user-documentation/layout-builder/staff-members/_index.md
- content/en/docs/user-documentation/layout-builder/testimonials/_index.md
- content/en/docs/wiki/_index.md
- Adds videos to all of the new components!
- Reorders the main content so that user docs are higher
> DS-253 LBv2 THE FINAL

- content/en/docs/user-documentation/layout-builder/accordion/_index.md
- content/en/docs/user-documentation/layout-builder/banner/_index.md
- content/en/docs/user-documentation/layout-builder/breadcrumbs/_index.md
- content/en/docs/user-documentation/layout-builder/cards/_index.md
- content/en/docs/user-documentation/layout-builder/carousel/_index.md
- content/en/docs/user-documentation/layout-builder/grid-cta/_index.md
- content/en/docs/user-documentation/layout-builder/modal/_index.md
- content/en/docs/user-documentation/layout-builder/partners/_index.md
- content/en/docs/user-documentation/layout-builder/ping-pong/_index.md
- content/en/docs/user-documentation/layout-builder/promo-card/_index.md
- content/en/docs/user-documentation/layout-builder/related-articles/_index.md
- content/en/docs/user-documentation/layout-builder/related-events/_index.md
- content/en/docs/user-documentation/layout-builder/simple-menu/_index.md
- content/en/docs/user-documentation/layout-builder/staff-members/_index.md
- content/en/docs/user-documentation/layout-builder/statistics/_index.md
- content/en/docs/user-documentation/layout-builder/table/_index.md
- content/en/docs/user-documentation/layout-builder/tabs/_index.md
- content/en/docs/user-documentation/layout-builder/testimonials/_index.md
- content/en/docs/user-documentation/layout-builder/webform/_index.md
[DS-674](https://yusa.atlassian.net/browse/DS-674): Update existing docs to point to new designs.
> DS-674 docs: Add Design System links to all components

- content/en/docs/content-structure/layout-builder/_index.md
Proper link https://ds-docs.y.org/img/designs/lb/Cards%20Desktop.png
> fix: URL to desktop

- content/en/docs/howto/migrate-to-lb/_index.md
- netlify.toml
https://yusa.atlassian.net/browse/DS-820 regarding LB migration, this feedback was given:
> Maybe we could also add some information on recommended deadlines if any. 
This adds some detail as to the timeline of the transition
> LB Migration Timeline

- content/en/docs/development/Important-versions-for-upgrade-path/_index.md
Check https://deploy-preview-66--sparkling-souffle-4f78b0.netlify.app/docs/development/important-versions-for-upgrade-path/
> feat: Add important releases

- content/en/blog/releases/release-ds-10.3.0.1.md
- content/en/blog/releases/release-vy-1.8.12.md
- content/en/docs/user-documentation/layout-builder/designs.md
- Add release notes:
- https://deploy-preview-67--sparkling-souffle-4f78b0.netlify.app/blog/2023/11/14/virtual-y-1.8.12/
- https://deploy-preview-67--sparkling-souffle-4f78b0.netlify.app/blog/2023/11/14/digital-services-release-10.3.0.1/
- Add UI Kit link
- https://deploy-preview-67--sparkling-souffle-4f78b0.netlify.app/docs/user-documentation/layout-builder/designs/#design-system
> docs: Add point release notes and link to UI Kit

- content/en/docs/development/Install-Solr-site-search-for-Open-Y/_index.md
- content/en/docs/howto/set-up-lb/_index.md
- Improve Canadian Colorway instructions
- Fix link, thanks to @carolpettirossi
> Misc post-release fixes

- content/en/docs/development/Important-versions-for-upgrade-path/_index.md
See https://yusa.atlassian.net/browse/DS-942?focusedCommentId=14292
> feat: Update _index.md

- content/en/docs/development/Important-versions-for-upgrade-path/_index.md
See https://github.com/YCloudYUSA/yusaopeny/releases/tag/10.3.2.2
> feat: Add 10.3.2.2 technical release

- content/en/docs/user-documentation/paragraphs/activity-finder/_index.md
https://github.com/YCloudYUSA/yusaopeny_activity_finder/pull/38
> Add a note about AF weeks filter

- content/en/docs/user-documentation/schedules/activity-finder/_index.md
Thanks to Christina from OneEach.
[Activity Finder - Block Configuration](https://deploy-preview-91--sparkling-souffle-4f78b0.netlify.app/docs/user-documentation/schedules/activity-finder/#block-configuration)
> docs: Clarify language around AF category filters

- content/en/docs/development/Upgrade_Use_Case_Drupal_9_Drupal_10_1/_index.md
- content/en/docs/development/_index.md
See https://deploy-preview-93--sparkling-souffle-4f78b0.netlify.app/docs/development/upgrade_use_case_drupal_9_drupal_10_1/
> feat: Add new Upgrade use case

- content/en/docs/user-documentation/layout-builder/header-footer/_index.md
as per https://www.drupal.org/node/3320855
Change on https://deploy-preview-105--sparkling-souffle-4f78b0.netlify.app/docs/user-documentation/layout-builder/header-footer/#copyright
> Update link to Block library
